app:
  entity-generator:
    enabled: true

logging:
  level:
    ru.tai: DEBUG

spring:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/news_service_db
    username: postgres
    password: postgres
    hikari:
      schema: app_schema