spring:
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/news_service_db
    username: postgres
    password: postgres
    hikari:
      schema: app_schema

app:
  entity-generator:
    enabled: true

logging:
  level:
    ru.tai: DEBUG